#Source: https://stackoverflow.com/questions/62909918/attributeerror-when-trying-to-rename-columns
df = df.rename(columns={'i_Team':'I Team', 'Full_Name':'Full Name'}, inplace = True)